services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - cookiejar_pgdata:/var/lib/postgresql/data
    networks:
      - cookiejar-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  migrate:
    image: cookiejar-api:blue
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
      FLASK_APP: app.py
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cookiejar-net
    command: >
      sh -lc "flask db upgrade"

  app_blue:
    image: cookiejar-api:blue
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
      APP_COLOR: blue
      APP_VERSION: "1.0.0"
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - cookiejar-net

  app_green:
    image: cookiejar-api:green
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
      APP_COLOR: green
      APP_VERSION: "1.0.1"
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - cookiejar-net

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app_blue
      - app_green
    networks:
      - cookiejar-net

  smoke:
    image: curlimages/curl:8.6.0
    depends_on:
      - nginx
    networks:
      - cookiejar-net
    volumes:
      - ./deployment/smoke.sh:/smoke.sh:ro
    entrypoint: ["/bin/sh", "/smoke.sh"]


networks:
  cookiejar-net:

volumes:
  cookiejar_pgdata:
