"""initial

Revision ID: 55cf61dc9a81
Revises: 
Create Date: 2025-12-26 18:14:06.418040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55cf61dc9a81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_category',
    sa.Column('tracker_category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracker_category', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('tracker_category_id'),
    sa.UniqueConstraint('tracker_category', name='uq_tracker_category')
    )
    op.create_table('tracker_purpose',
    sa.Column('tracker_purpose_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracker_purpose', sa.String(length=5000), nullable=False),
    sa.PrimaryKeyConstraint('tracker_purpose_id'),
    sa.UniqueConstraint('tracker_purpose', name='uq_tracker_purpose')
    )
    op.create_table('tracker_source',
    sa.Column('tracker_source_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracker_source', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('tracker_source_id'),
    sa.UniqueConstraint('tracker_source', name='uq_tracker_source')
    )
    op.create_table('tracker_type',
    sa.Column('tracker_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracker_type', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('tracker_type_id'),
    sa.UniqueConstraint('tracker_type', name='uq_tracker_type')
    )
    op.create_table('vendor',
    sa.Column('vendor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('vendor_id'),
    sa.UniqueConstraint('vendor_name', name='uq_vendor_name')
    )
    op.create_table('vendor_description',
    sa.Column('vendor_description_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_description', sa.String(length=5000), nullable=False),
    sa.PrimaryKeyConstraint('vendor_description_id'),
    sa.UniqueConstraint('vendor_description', name='uq_vendor_description')
    )
    op.create_table('tracking_domain',
    sa.Column('tracking_domain_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('tracking_domain', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.vendor_id'], ),
    sa.PrimaryKeyConstraint('tracking_domain_id'),
    sa.UniqueConstraint('vendor_id', 'tracking_domain', name='uq_vendor_id_tracking_domain')
    )
    op.create_table('vendor_descriptions',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_description_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_description_id'], ['vendor_description.vendor_description_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.vendor_id'], ),
    sa.PrimaryKeyConstraint('vendor_id', 'vendor_description_id'),
    sa.UniqueConstraint('vendor_id', 'vendor_description_id', 'is_current', name='uq_vendor_id_vendor_description_id_is_current')
    )
    with op.batch_alter_table('vendor_descriptions', schema=None) as batch_op:
        batch_op.create_index('idx_vendor_descriptions_composite', ['vendor_id', 'vendor_description_id', 'is_current'], unique=False)

    op.create_table('tracker',
    sa.Column('tracker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracker_type_id', sa.Integer(), nullable=False),
    sa.Column('tracker_category_id', sa.Integer(), nullable=False),
    sa.Column('tracker_source_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('tracking_domain_id', sa.Integer(), nullable=False),
    sa.Column('tracker_name', sa.String(length=255), nullable=True),
    sa.Column('tracker_duration', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tracker_category_id'], ['tracker_category.tracker_category_id'], ),
    sa.ForeignKeyConstraint(['tracker_source_id'], ['tracker_source.tracker_source_id'], ),
    sa.ForeignKeyConstraint(['tracker_type_id'], ['tracker_type.tracker_type_id'], ),
    sa.ForeignKeyConstraint(['tracking_domain_id'], ['tracking_domain.tracking_domain_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.vendor_id'], ),
    sa.PrimaryKeyConstraint('tracker_id'),
    sa.UniqueConstraint('tracker_name', 'tracker_type_id', 'tracking_domain_id', name='uq_tracker_name_type_domain')
    )
    with op.batch_alter_table('tracker', schema=None) as batch_op:
        batch_op.create_index('idx_tracker_composite', ['tracker_type_id', 'tracker_name', 'tracking_domain_id'], unique=False)

    op.create_table('tracker_purposes',
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('tracker_purpose_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tracker_id'], ['tracker.tracker_id'], ),
    sa.ForeignKeyConstraint(['tracker_purpose_id'], ['tracker_purpose.tracker_purpose_id'], ),
    sa.PrimaryKeyConstraint('tracker_id', 'tracker_purpose_id'),
    sa.UniqueConstraint('tracker_id', 'tracker_purpose_id', 'is_current', name='uq_tracker_id_tracker_purpose_id_is_current')
    )
    with op.batch_alter_table('tracker_purposes', schema=None) as batch_op:
        batch_op.create_index('idx_tracker_purposes_composite', ['tracker_id', 'tracker_purpose_id', 'is_current'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_purposes', schema=None) as batch_op:
        batch_op.drop_index('idx_tracker_purposes_composite')

    op.drop_table('tracker_purposes')
    with op.batch_alter_table('tracker', schema=None) as batch_op:
        batch_op.drop_index('idx_tracker_composite')

    op.drop_table('tracker')
    with op.batch_alter_table('vendor_descriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_vendor_descriptions_composite')

    op.drop_table('vendor_descriptions')
    op.drop_table('tracking_domain')
    op.drop_table('vendor_description')
    op.drop_table('vendor')
    op.drop_table('tracker_type')
    op.drop_table('tracker_source')
    op.drop_table('tracker_purpose')
    op.drop_table('tracker_category')
    # ### end Alembic commands ###
