services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 2s
      timeout: 2s
      retries: 30
    networks: [cookiejar-net]

  migrate:
    image: cookiejar-api:${IMAGE_TAG}
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
      FLASK_APP: app.py
    depends_on:
      db:
        condition: service_healthy
    networks: [cookiejar-net]
    command: >
      sh -lc "flask db upgrade"

  app:
    image: cookiejar-api:${IMAGE_TAG}
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
      APP_COLOR: green
      APP_VERSION: ${IMAGE_TAG}
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - cookiejar-net

  nginx:
    image: cookiejar-nginx:${IMAGE_TAG}
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - cookiejar-net

networks:
  cookiejar-net:

volumes:
  cookiejar_pgdata:
