services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 2s
      timeout: 2s
      retries: 30
    networks: [cookiejar-net]

  migrate:
    image: cookiejar-api:68
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
      FLASK_APP: app.py
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cookiejar-net
    command: >
      sh -lc "flask db upgrade"

  app_blue:
    image: cookiejar-api:67
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
      APP_COLOR: blue
      APP_VERSION: "67"
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - cookiejar-net

  app_green:
    image: cookiejar-api:68
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
      APP_COLOR: green
      APP_VERSION: "68"
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - cookiejar-net

  nginx:
    image: cookiejar-nginx:test
    ports:
      - "8088:80"
    depends_on:
      - app_blue
      - app_green
    networks:
      - cookiejar-net
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  cookiejar-net:

volumes:
  cookiejar_pgdata: