services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - cookiejar-net

  migrate:
    image: ghcr.io/angelamadjar/cookiejar-api:dev
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
      FLASK_APP: app.py
    depends_on:
      - db
    command: sh -lc "flask db upgrade"
    networks:
      - cookiejar-net

  app:
    image: ghcr.io/angelamadjar/cookiejar-api:dev
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
      APP_COLOR: green
      APP_VERSION: dev
    depends_on:
      - migrate
    networks:
      - cookiejar-net

  nginx:
    image: ghcr.io/angelamadjar/cookiejar-nginx:dev
    ports:
      - "8088:80"
    depends_on:
      - app
    networks:
      - cookiejar-net

networks:
  cookiejar-net: