name: Deploy to Dev (Mac)

on:
  workflow_run:
    workflows: ["Homework 5 CI"]
    types: [completed]
    branches: [dev]

jobs:
  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'dev'
    environment: development
    runs-on: [self-hosted, macOS, ARM64]

    env:
      IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
      APP_VERSION: dev-${{ github.event.workflow_run.head_sha }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DATABASE_URL: postgresql+psycopg2://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull latest images
        run: |
          docker pull ghcr.io/angelamadjar/cookiejar-api:${IMAGE_TAG}
          docker pull ghcr.io/angelamadjar/cookiejar-nginx:${IMAGE_TAG}

      # - name: Redeploy dev app stack
      #   run: |
      #     export APP_VERSION=dev-$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-8)
      #     docker compose -f deployment/homework-5/dev/docker-compose.dev.yml down -v --remove-orphans
      #     docker compose -f deployment/homework-5/dev/docker-compose.dev.yml up -d

      - name: Redeploy dev app stack
        run: |
          COMPOSE="docker compose -f deployment/homework-5/dev/docker-compose.dev.yml"

          $COMPOSE pull app nginx migrate
          $COMPOSE up -d db
          $COMPOSE up migrate
          $COMPOSE up -d --force-recreate app nginx

      - name: Verify deployment
        run: |
          sleep 10
          curl -fsS http://localhost:8088/health
          curl -fsS http://localhost:8088/version

# test